-- \i 'C:\\Users\\PELTOVI\\Desktop\\Muut\\PostgresBackup.sql'
-- Postgresql version 16.10
-- pg_dump version 18.0

-- Create roles
\restrict 3POPBY2f7k9Qa5OkTzXHSrO6XZ7BZecC35iibh5YYHggcJ86lIE3F1gBdltZ86q
CREATE ROLE commonapi;
ALTER ROLE commonapi WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS PASSWORD 'common-password';

CREATE ROLE commondataapi;
ALTER ROLE commondataapi WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS PASSWORD 'commondata-password';

CREATE ROLE database1;
ALTER ROLE database1 WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS PASSWORD 'database1-password';

CREATE ROLE database1api;
ALTER ROLE database1api WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS PASSWORD 'database1api-password';

CREATE ROLE database1dataupdate;
ALTER ROLE database1dataupdate WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS PASSWORD 'database1dataupdate-password';

CREATE ROLE database2;
ALTER ROLE database2 WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS PASSWORD 'database2-password';

CREATE ROLE database2api;
ALTER ROLE database2api WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS PASSWORD 'database2api-password';

CREATE ROLE database2dataupdate;
ALTER ROLE database2dataupdate WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS PASSWORD 'database2dataupdate-password';

CREATE ROLE dataupdateapi;
ALTER ROLE dataupdateapi WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS PASSWORD 'dataupdateapi-password';
\unrestrict 3POPBY2f7k9Qa5OkTzXHSrO6XZ7BZecC35iibh5YYHggcJ86lIE3F1gBdltZ86q
\restrict SpVmfADflPxSTDVQQd2G4alv3wscSuyrOoXiNeZ3dxWT57tnXgYb76lxDJCtCtc
-- Create databases
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: common; Type: DATABASE; Schema: -; Owner: commonapi
--

CREATE DATABASE common WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'Finnish_Finland.1252';

ALTER DATABASE common OWNER TO commonapi;

\unrestrict SpVmfADflPxSTDVQQd2G4alv3wscSuyrOoXiNeZ3dxWT57tnXgYb76lxDJCtCtc
\connect common
\restrict SpVmfADflPxSTDVQQd2G4alv3wscSuyrOoXiNeZ3dxWT57tnXgYb76lxDJCtCtc

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: API; Type: TABLE; Schema: public; Owner: commonapi
--

CREATE TABLE public."API" (
    "Active" boolean DEFAULT true,
    "Created" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "Creator" uuid NOT NULL,
	"Deleted" timestamp with time zone,
    "LastUsed" timestamp with time zone,
    "Id" character varying(50) NOT NULL,
    "Organisation" uuid NOT NULL
);


ALTER TABLE public."API" OWNER TO commonapi;

--
-- Name: DB; Type: TABLE; Schema: public; Owner: commonapi
--

CREATE TABLE public."DB" (
    "ChartFetch" integer DEFAULT 0,
    "DBId" text NOT NULL,
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "IdNumber" integer,
    "Name" text NOT NULL
);


ALTER TABLE public."DB" OWNER TO commonapi;

--
-- Name: ChartDataFetchSettings; Type: TABLE; Schema: public; Owner: commonapi
--

CREATE TABLE IF NOT EXISTS public."ChartDataFetchSettings"
(
    "Id" integer NOT NULL,
    "Day1" text,
    "Day2" text,
    "Day3" text,
    "Day7" text,
    "Day14" text,
    "Day30" text,
    "Day90" text,
    "Day180" text,
    "Day365" text
);


ALTER TABLE public."ChartDataFetchSettings" OWNER TO commonapi;

--
-- Name: DashboardDefault; Type: TABLE; Schema: public; Owner: commonapi
--

CREATE TABLE public."DashboardDefault" (
    "Id" character varying(36) DEFAULT (gen_random_uuid())::text NOT NULL,
    "Dashboard" jsonb DEFAULT '[]'::jsonb
);


ALTER TABLE public."DashboardDefault" OWNER TO commonapi;

--
-- Name: Locale; Type: TABLE; Schema: public; Owner: commonapi
--

CREATE TABLE public."Locale" (
    "Id" integer NOT NULL,
    "Key" text NOT NULL,
    "Language" text NOT NULL,
    "Message" text NOT NULL,
    "Topic" text NOT NULL,
    "Type" text NOT NULL
);


ALTER TABLE public."Locale" OWNER TO commonapi;

--
-- Name: Locale_Id_seq; Type: SEQUENCE; Schema: public; Owner: commonapi
--

ALTER TABLE public."Locale" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Locale_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Organisation; Type: TABLE; Schema: public; Owner: commonapi
--

CREATE TABLE public."Organisation" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "Created" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "DeletedItems" text[],
    "Deleted" timestamp with time zone,
    "Disabled" boolean DEFAULT false,
    "Name" text NOT NULL,
    "Type" integer,
    "Updated" timestamp with time zone
);


ALTER TABLE public."Organisation" OWNER TO commonapi;

--
-- Name: ResetTokens; Type: TABLE; Schema: public; Owner: commonapi
--

CREATE TABLE public."ResetTokens" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "Created" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "Expiry" timestamp with time zone,
    "Token" text NOT NULL,
    "Used" timestamp with time zone,
    "UserId" uuid NOT NULL
);


ALTER TABLE public."ResetTokens" OWNER TO commonapi;

--
-- Name: SensorSettings; Type: TABLE; Schema: public; Owner: commonapi
--

CREATE TABLE public."SensorSettings" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "Created" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "Deleted" timestamp with time zone,
    "Disabled" boolean DEFAULT false,
    "DisplayDashboard" boolean DEFAULT false,
    "DBID" text NOT NULL,
    "DBVALUE" text NOT NULL,
    "DeviceSource" text DEFAULT ''::text,
    "Name" text NOT NULL,
    "Organisation" uuid NOT NULL,
    "Shared" integer DEFAULT 0 NOT NULL,
    "Unit" text DEFAULT ''::text,
    "Updated" timestamp with time zone,
    "ValueChange" double precision DEFAULT 1.0
);


ALTER TABLE public."SensorSettings" OWNER TO commonapi;

--
-- Name: User; Type: TABLE; Schema: public; Owner: commonapi
--

CREATE TABLE public."User" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "Access" text DEFAULT 'user'::text,
    "Created" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "Deleted" timestamp with time zone,
    "Disabled" boolean DEFAULT false,
    "Email" text NOT NULL,
    "FailedLogins" integer DEFAULT 0,
    "LastLogin" timestamp with time zone,
    "Name" text NOT NULL,
    "Organisation" uuid,
    "Password" text,
    "Updated" timestamp with time zone,
    "Registered" timestamp with time zone
);


ALTER TABLE public."User" OWNER TO commonapi;

--
-- Data for Name: ChartDataFetchSettings; Type: TABLE DATA; Schema: public; Owner: commonapi
--

INSERT INTO public."ChartDataFetchSettings"(
	"Id", "Day1", "Day2", "Day3", "Day7", "Day14", "Day30", "Day90", "Day180", "Day365")
	VALUES (0, 'null', 'null', 'null', '30 minute', '1 hour', '2 hour', '6 hour', '12 hour', '1 day');

--
-- Data for Name: DB; Type: TABLE DATA; Schema: public; Owner: commonapi
--

INSERT INTO public."DB" ("Id", "IdNumber", "Name", "DBId") VALUES ('83222e4b-121f-4667-9aee-f49700026a84', 2, 'Database2', 'database2');
INSERT INTO public."DB" ("Id", "IdNumber", "Name", "DBId") VALUES ('d6e05ec4-7842-4fa7-922f-d4accceef063', 1, 'Database1', 'database1');
INSERT INTO public."DB" ("Id", "IdNumber", "Name", "DBId") VALUES ('24678880-7b23-4db6-892a-26fbfe2a14a0', 3, 'CommonData', 'commondata');
INSERT INTO public."DB" ("Id", "IdNumber", "Name", "DBId") VALUES ('1bfe21dd-1fe2-4ea6-83ce-6d1561fa8b27', 4, 'None', 'none');

--
-- Data for Name: Locale; Type: TABLE_DATA; Schema: public; Owner: commonapi
--

INSERT INTO public."Locale"("Key", "Language", "Message", "Topic", "Type") VALUES ('create_user', 'universal', 'Hi,<br/><br/>[sender] ([organisation]) has send an invitation to register your [appname] Dashboard account.<br/><br/>You can register your account using <a href="[link]">this link</a>.<br/><br/>Best regards,<br/>[appname]<br/><br/>Hi,<br/><br/>[sender] ([organisation]) on lähettänyt kutsun rekisteröidä [appname] Dashboard -tilisi.<br/><br/>Voit rekisteröidä tilisi <a href="[link]">tällä linkillä</a>.<br/><br/>Parhain terveisin,<br/>[appname]', 'email');
INSERT INTO public."Locale"("Key", "Language", "Message", "Topic", "Type") VALUES ('resend_invite', 'universal', 'Hi,<br/><br/>[sender] ([organisation]) has renewed the registration for your [appname] Dashboard account.<br/><br/>You can register your account using <a href="[link]">this link</a>.<br/><br/>Best regards,<br/>[appname]<br/><br/>Hi,<br/><br/>[sender] ([organisation]) on uudelleen lähettänyt kutsun [appname] Dashboard -tilisi rekisteröintiin.<br/><br/>Voit rekisteröidä tilisi <a href="[link]">tällä linkillä</a>.<br/><br/>Parhain terveisin,<br/>[appname]', 'email');

--
-- Data for Name: Organisation; Type: TABLE DATA; Schema: public; Owner: commonapi
--

INSERT INTO public."Organisation" ("Id", "Name", "Type") VALUES ('3b800405-9237-4b2a-8d49-c287daf68557', 'Admin organisation', 0);

--
-- Data for Name: User; Type: TABLE DATA; Schema: public; Owner: commonapi
--

-- Admin user password without quotes "demoDEMO123!"
INSERT INTO public."User" ("Id", "Access", "Email", "Name", "Organisation", "Password", "Registered") VALUES ('4227de34-7b6a-487d-ad37-51d4afdaf97b', 'appadmin', 'admin@dashboard.com', 'Dashboard admin', '3b800405-9237-4b2a-8d49-c287daf68557', '$2a$12$Vg8fzAkB5p37ERfPvZbFO.5N0E5b86LBOwcfZwouTxHdjFxlZSMrG', '2026-06-01 00:00:00.000000+03');



--
-- Name: Locale_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: commonapi
--

SELECT pg_catalog.setval('public."Locale_Id_seq"', 1, false);


--
-- Name: API API_pkey; Type: CONSTRAINT; Schema: public; Owner: commonapi
--

ALTER TABLE ONLY public."API"
    ADD CONSTRAINT "API_pkey" PRIMARY KEY ("Id");


--
-- Name: DB PK_ChartDataFetchSettings; Type: CONSTRAINT; Schema: public; Owner: commonapi
--

ALTER TABLE ONLY public."ChartDataFetchSettings"
    ADD CONSTRAINT "PK_ChartDataFetchSettings" PRIMARY KEY ("Id");


--
-- Name: DB PK_DB; Type: CONSTRAINT; Schema: public; Owner: commonapi
--

ALTER TABLE ONLY public."DB"
    ADD CONSTRAINT "PK_DB" PRIMARY KEY ("Id");


--
-- Name: DashboardDefault PK_DashboardDefault; Type: CONSTRAINT; Schema: public; Owner: commonapi
--

ALTER TABLE ONLY public."DashboardDefault"
    ADD CONSTRAINT "PK_DashboardDefault" PRIMARY KEY ("Id");


--
-- Name: Locale PK_Locale; Type: CONSTRAINT; Schema: public; Owner: commonapi
--

ALTER TABLE ONLY public."Locale"
    ADD CONSTRAINT "PK_Locale" PRIMARY KEY ("Id");


--
-- Name: Organisation PK_Organisation; Type: CONSTRAINT; Schema: public; Owner: commonapi
--

ALTER TABLE ONLY public."Organisation"
    ADD CONSTRAINT "PK_Organisation" PRIMARY KEY ("Id");


--
-- Name: ResetTokens PK_ResetTokens; Type: CONSTRAINT; Schema: public; Owner: commonapi
--

ALTER TABLE ONLY public."ResetTokens"
    ADD CONSTRAINT "PK_ResetTokens" PRIMARY KEY ("Id");


--
-- Name: SensorSettings PK_SensorSettings; Type: CONSTRAINT; Schema: public; Owner: commonapi
--

ALTER TABLE ONLY public."SensorSettings"
    ADD CONSTRAINT "PK_SensorSettings" PRIMARY KEY ("Id");


--
-- Name: User PK_User; Type: CONSTRAINT; Schema: public; Owner: commonapi
--

ALTER TABLE ONLY public."User"
    ADD CONSTRAINT "PK_User" PRIMARY KEY ("Id");


--
-- Name: IX_DB_Id; Type: INDEX; Schema: public; Owner: commonapi
--

CREATE UNIQUE INDEX "IX_DB_Id" ON public."DB" USING btree ("Id");


--
-- Name: IX_DashboardDefault_Id; Type: INDEX; Schema: public; Owner: commonapi
--

CREATE UNIQUE INDEX "IX_DashboardDefault_Id" ON public."DashboardDefault" USING btree ("Id");


--
-- Name: IX_Locale_Id; Type: INDEX; Schema: public; Owner: commonapi
--

CREATE UNIQUE INDEX "IX_Locale_Id" ON public."Locale" USING btree ("Id");


--
-- Name: IX_Organisation_Id; Type: INDEX; Schema: public; Owner: commonapi
--

CREATE UNIQUE INDEX "IX_Organisation_Id" ON public."Organisation" USING btree ("Id");


--
-- Name: IX_ResetTokens_Id; Type: INDEX; Schema: public; Owner: commonapi
--

CREATE UNIQUE INDEX "IX_ResetTokens_Id" ON public."ResetTokens" USING btree ("Id");


--
-- Name: IX_SensorSettings_Id; Type: INDEX; Schema: public; Owner: commonapi
--

CREATE UNIQUE INDEX "IX_SensorSettings_Id" ON public."SensorSettings" USING btree ("Id");


--
-- Name: IX_User_Id; Type: INDEX; Schema: public; Owner: commonapi
--

CREATE UNIQUE INDEX "IX_User_Id" ON public."User" USING btree ("Id");
\unrestrict SpVmfADflPxSTDVQQd2G4alv3wscSuyrOoXiNeZ3dxWT57tnXgYb76lxDJCtCtc

--
-- Database "commondata"
--

\restrict M4HKvMuCFaZku5MaVlcTHU8cfSh1Zb3B7wUyCNkTCK97tQwxaRRSgvjKbQsueCA

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: commondata; Type: DATABASE; Schema: -; Owner: commondataapi
--

CREATE DATABASE commondata WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'Finnish_Finland.1252';


ALTER DATABASE commondata OWNER TO commondataapi;

\unrestrict M4HKvMuCFaZku5MaVlcTHU8cfSh1Zb3B7wUyCNkTCK97tQwxaRRSgvjKbQsueCA
\connect commondata
\restrict M4HKvMuCFaZku5MaVlcTHU8cfSh1Zb3B7wUyCNkTCK97tQwxaRRSgvjKbQsueCA

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: ElectricityPriceData; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."ElectricityPriceData" (
    "Id" integer NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "Value" double precision NOT NULL
);


ALTER TABLE public."ElectricityPriceData" OWNER TO postgres;

--
-- Name: ElectricityPriceData_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."ElectricityPriceData_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public."ElectricityPriceData_Id_seq" OWNER TO postgres;

--
-- Name: ElectricityPriceData_Id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."ElectricityPriceData_Id_seq" OWNED BY public."ElectricityPriceData"."Id";


--
-- Name: WeatherDataCloudiness; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."WeatherDataCloudiness" (
    "Id" integer NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "Value" double precision NOT NULL
);


ALTER TABLE public."WeatherDataCloudiness" OWNER TO postgres;

--
-- Name: WeatherDataCloudiness_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."WeatherDataCloudiness_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public."WeatherDataCloudiness_Id_seq" OWNER TO postgres;

--
-- Name: WeatherDataCloudiness_Id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."WeatherDataCloudiness_Id_seq" OWNED BY public."WeatherDataCloudiness"."Id";


--
-- Name: WeatherDataTemperature; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."WeatherDataTemperature" (
    "Id" integer NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "Value" double precision NOT NULL
);


ALTER TABLE public."WeatherDataTemperature" OWNER TO postgres;

--
-- Name: WeatherDataTemperature_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."WeatherDataTemperature_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public."WeatherDataTemperature_Id_seq" OWNER TO postgres;

--
-- Name: WeatherDataTemperature_Id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."WeatherDataTemperature_Id_seq" OWNED BY public."WeatherDataTemperature"."Id";


--
-- Name: WeatherDataWindspeed; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."WeatherDataWindspeed" (
    "Id" integer NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "Value" double precision NOT NULL
);


ALTER TABLE public."WeatherDataWindspeed" OWNER TO postgres;

--
-- Name: WeatherDataWindspeed_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."WeatherDataWindspeed_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public."WeatherDataWindspeed_Id_seq" OWNER TO postgres;

--
-- Name: WeatherDataWindspeed_Id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."WeatherDataWindspeed_Id_seq" OWNED BY public."WeatherDataWindspeed"."Id";


--
-- Name: WeatherForecastDataCloudiness; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."WeatherForecastDataCloudiness" (
    "Id" integer NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "Value" double precision NOT NULL
);


ALTER TABLE public."WeatherForecastDataCloudiness" OWNER TO postgres;

--
-- Name: WeatherForecastDataCloudiness_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."WeatherForecastDataCloudiness_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public."WeatherForecastDataCloudiness_Id_seq" OWNER TO postgres;

--
-- Name: WeatherForecastDataCloudiness_Id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."WeatherForecastDataCloudiness_Id_seq" OWNED BY public."WeatherForecastDataCloudiness"."Id";


--
-- Name: WeatherForecastDataTemperature; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."WeatherForecastDataTemperature" (
    "Id" integer NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "Value" double precision NOT NULL
);


ALTER TABLE public."WeatherForecastDataTemperature" OWNER TO postgres;

--
-- Name: WeatherForecastDataTemperature_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."WeatherForecastDataTemperature_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public."WeatherForecastDataTemperature_Id_seq" OWNER TO postgres;

--
-- Name: WeatherForecastDataTemperature_Id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."WeatherForecastDataTemperature_Id_seq" OWNED BY public."WeatherForecastDataTemperature"."Id";


--
-- Name: WeatherForecastDataWindspeed; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."WeatherForecastDataWindspeed" (
    "Id" integer NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "Value" double precision NOT NULL
);


ALTER TABLE public."WeatherForecastDataWindspeed" OWNER TO postgres;

--
-- Name: WeatherForecastDataWindspeed_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."WeatherForecastDataWindspeed_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public."WeatherForecastDataWindspeed_Id_seq" OWNER TO postgres;

--
-- Name: WeatherForecastDataWindspeed_Id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."WeatherForecastDataWindspeed_Id_seq" OWNED BY public."WeatherForecastDataWindspeed"."Id";


--
-- Name: ElectricityPriceData Id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ElectricityPriceData" ALTER COLUMN "Id" SET DEFAULT nextval('public."ElectricityPriceData_Id_seq"'::regclass);


--
-- Name: WeatherDataCloudiness Id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."WeatherDataCloudiness" ALTER COLUMN "Id" SET DEFAULT nextval('public."WeatherDataCloudiness_Id_seq"'::regclass);


--
-- Name: WeatherDataTemperature Id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."WeatherDataTemperature" ALTER COLUMN "Id" SET DEFAULT nextval('public."WeatherDataTemperature_Id_seq"'::regclass);


--
-- Name: WeatherDataWindspeed Id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."WeatherDataWindspeed" ALTER COLUMN "Id" SET DEFAULT nextval('public."WeatherDataWindspeed_Id_seq"'::regclass);


--
-- Name: WeatherForecastDataCloudiness Id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."WeatherForecastDataCloudiness" ALTER COLUMN "Id" SET DEFAULT nextval('public."WeatherForecastDataCloudiness_Id_seq"'::regclass);


--
-- Name: WeatherForecastDataTemperature Id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."WeatherForecastDataTemperature" ALTER COLUMN "Id" SET DEFAULT nextval('public."WeatherForecastDataTemperature_Id_seq"'::regclass);


--
-- Name: WeatherForecastDataWindspeed Id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."WeatherForecastDataWindspeed" ALTER COLUMN "Id" SET DEFAULT nextval('public."WeatherForecastDataWindspeed_Id_seq"'::regclass);


--
-- Name: ElectricityPriceData_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."ElectricityPriceData_Id_seq"', 28333, true);


--
-- Name: WeatherDataCloudiness_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."WeatherDataCloudiness_Id_seq"', 186629, true);


--
-- Name: WeatherDataTemperature_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."WeatherDataTemperature_Id_seq"', 186644, true);


--
-- Name: WeatherDataWindspeed_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."WeatherDataWindspeed_Id_seq"', 186232, true);


--
-- Name: WeatherForecastDataCloudiness_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."WeatherForecastDataCloudiness_Id_seq"', 4700, true);


--
-- Name: WeatherForecastDataTemperature_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."WeatherForecastDataTemperature_Id_seq"', 4700, true);


--
-- Name: WeatherForecastDataWindspeed_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."WeatherForecastDataWindspeed_Id_seq"', 4700, true);


--
-- Name: ElectricityPriceData ElectricityPriceData_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ElectricityPriceData"
    ADD CONSTRAINT "ElectricityPriceData_pkey" PRIMARY KEY ("Id");


--
-- Name: WeatherDataCloudiness WeatherDataCloudiness_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."WeatherDataCloudiness"
    ADD CONSTRAINT "WeatherDataCloudiness_pkey" PRIMARY KEY ("Id");


--
-- Name: WeatherDataTemperature WeatherDataTemperature_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."WeatherDataTemperature"
    ADD CONSTRAINT "WeatherDataTemperature_pkey" PRIMARY KEY ("Id");


--
-- Name: WeatherDataWindspeed WeatherDataWindspeed_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."WeatherDataWindspeed"
    ADD CONSTRAINT "WeatherDataWindspeed_pkey" PRIMARY KEY ("Id");


--
-- Name: WeatherForecastDataCloudiness WeatherForecastDataCloudiness_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."WeatherForecastDataCloudiness"
    ADD CONSTRAINT "WeatherForecastDataCloudiness_pkey" PRIMARY KEY ("Id");


--
-- Name: WeatherForecastDataTemperature WeatherForecastDataTemperature_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."WeatherForecastDataTemperature"
    ADD CONSTRAINT "WeatherForecastDataTemperature_pkey" PRIMARY KEY ("Id");


--
-- Name: WeatherForecastDataWindspeed WeatherForecastDataWindspeed_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."WeatherForecastDataWindspeed"
    ADD CONSTRAINT "WeatherForecastDataWindspeed_pkey" PRIMARY KEY ("Id");


--
-- Name: TABLE "ElectricityPriceData"; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT ON TABLE public."ElectricityPriceData" TO commondataapi;
GRANT INSERT ON TABLE public."ElectricityPriceData" TO dataupdateapi;


--
-- Name: SEQUENCE "ElectricityPriceData_Id_seq"; Type: ACL; Schema: public; Owner: postgres
--

GRANT UPDATE ON SEQUENCE public."ElectricityPriceData_Id_seq" TO dataupdateapi;


--
-- Name: TABLE "WeatherDataCloudiness"; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT ON TABLE public."WeatherDataCloudiness" TO commondataapi;
GRANT INSERT ON TABLE public."WeatherDataCloudiness" TO dataupdateapi;


--
-- Name: SEQUENCE "WeatherDataCloudiness_Id_seq"; Type: ACL; Schema: public; Owner: postgres
--

GRANT UPDATE ON SEQUENCE public."WeatherDataCloudiness_Id_seq" TO dataupdateapi;


--
-- Name: TABLE "WeatherDataTemperature"; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT ON TABLE public."WeatherDataTemperature" TO commondataapi;
GRANT INSERT ON TABLE public."WeatherDataTemperature" TO dataupdateapi;


--
-- Name: SEQUENCE "WeatherDataTemperature_Id_seq"; Type: ACL; Schema: public; Owner: postgres
--

GRANT UPDATE ON SEQUENCE public."WeatherDataTemperature_Id_seq" TO dataupdateapi;


--
-- Name: TABLE "WeatherDataWindspeed"; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT ON TABLE public."WeatherDataWindspeed" TO commondataapi;
GRANT INSERT ON TABLE public."WeatherDataWindspeed" TO dataupdateapi;


--
-- Name: SEQUENCE "WeatherDataWindspeed_Id_seq"; Type: ACL; Schema: public; Owner: postgres
--

GRANT UPDATE ON SEQUENCE public."WeatherDataWindspeed_Id_seq" TO dataupdateapi;


--
-- Name: TABLE "WeatherForecastDataCloudiness"; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT ON TABLE public."WeatherForecastDataCloudiness" TO commondataapi;
GRANT INSERT,DELETE ON TABLE public."WeatherForecastDataCloudiness" TO dataupdateapi;


--
-- Name: SEQUENCE "WeatherForecastDataCloudiness_Id_seq"; Type: ACL; Schema: public; Owner: postgres
--

GRANT UPDATE ON SEQUENCE public."WeatherForecastDataCloudiness_Id_seq" TO dataupdateapi;


--
-- Name: TABLE "WeatherForecastDataTemperature"; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT ON TABLE public."WeatherForecastDataTemperature" TO commondataapi;
GRANT INSERT,DELETE ON TABLE public."WeatherForecastDataTemperature" TO dataupdateapi;


--
-- Name: SEQUENCE "WeatherForecastDataTemperature_Id_seq"; Type: ACL; Schema: public; Owner: postgres
--

GRANT UPDATE ON SEQUENCE public."WeatherForecastDataTemperature_Id_seq" TO dataupdateapi;


--
-- Name: TABLE "WeatherForecastDataWindspeed"; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT ON TABLE public."WeatherForecastDataWindspeed" TO commondataapi;
GRANT INSERT,DELETE ON TABLE public."WeatherForecastDataWindspeed" TO dataupdateapi;


--
-- Name: SEQUENCE "WeatherForecastDataWindspeed_Id_seq"; Type: ACL; Schema: public; Owner: postgres
--

GRANT UPDATE ON SEQUENCE public."WeatherForecastDataWindspeed_Id_seq" TO dataupdateapi;

\unrestrict M4HKvMuCFaZku5MaVlcTHU8cfSh1Zb3B7wUyCNkTCK97tQwxaRRSgvjKbQsueCA

--
-- Database "database1" dump
--

\restrict cDDh48PM931am18VgGa0zXmIGZ0hT3ED7T9QBwpJGpOaqijeNhUyk4MY71o3eFr

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: database1; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE database1 WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'Finnish_Finland.1252';


ALTER DATABASE database1 OWNER TO postgres;

\unrestrict cDDh48PM931am18VgGa0zXmIGZ0hT3ED7T9QBwpJGpOaqijeNhUyk4MY71o3eFr
\connect database1
\restrict cDDh48PM931am18VgGa0zXmIGZ0hT3ED7T9QBwpJGpOaqijeNhUyk4MY71o3eFr

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: DATABASE database1; Type: ACL; Schema: -; Owner: postgres
--

GRANT TEMPORARY ON DATABASE database1 TO database1api;
GRANT TEMPORARY ON DATABASE database1 TO dataupdateapi;

\unrestrict cDDh48PM931am18VgGa0zXmIGZ0hT3ED7T9QBwpJGpOaqijeNhUyk4MY71o3eFr

--
-- Database "database2" dump
--

\restrict 3TmJKxjyuP9AM8GpNxUTGiNkSmmIjoxBaVDju8N430FMBTiELZWt0puhtVz6Oob

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: database2; Type: DATABASE; Schema: -; Owner: database2api
--

CREATE DATABASE database2 WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'Finnish_Finland.1252';


ALTER DATABASE database2 OWNER TO database2api;

\unrestrict 3TmJKxjyuP9AM8GpNxUTGiNkSmmIjoxBaVDju8N430FMBTiELZWt0puhtVz6Oob